#!/bin/bash

set -e

error=

if ! git config --get user.email >/dev/null; then
    echo "Error: cannot backup current files in $HOME unless git config user.email is set"
    echo 'Please run `git config --global user.email you@email.com` first'
    echo
    error=y
fi

if ! git config --get user.name >/dev/null; then
    echo "Error: cannot backup current files in $HOME unless git config user.name is set"
    echo 'Please run `git config --global user.name your_name` first'
    echo
    error=y
fi

if [ -e ~/.git ]; then
    echo "Error: $HOME/.git already exists"
    error=y
fi

if [ -n "$error" ]; then
    exit 1
fi

set -x

pushd "$HOME" >/dev/null
git clone --bare https://github.com/kevorr/dotfiles .git

GIT_DIR=.git git --bare config core.bare false
git reset --soft master
git stash save "local dotfiles backup"
git checkout .
git config status.showUntrackedFiles no

popd

if type "$0" >/dev/null; then
   exec "$0"
fi
